version: '3'

services:
  map:
    image: overv/openstreetmap-tile-server
    environment:
      - ALLOW_CORS=enabled
      - FLAT_NODES=enabled
    volumes:
      - osm-data:/data/database/
    ports:
      - 8080:80
      - 5432:5432
    command: "run"
    restart: always
volumes:
  osm-data:
